/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin/AdminDashboard': RouteRecordInfo<'/admin/AdminDashboard', '/admin/AdminDashboard', Record<never, never>, Record<never, never>>,
    '/admin/teams/TeamForm': RouteRecordInfo<'/admin/teams/TeamForm', '/admin/teams/TeamForm', Record<never, never>, Record<never, never>>,
    '/admin/teams/TeamsOverview': RouteRecordInfo<'/admin/teams/TeamsOverview', '/admin/teams/TeamsOverview', Record<never, never>, Record<never, never>>,
    '/LoginCallback': RouteRecordInfo<'/LoginCallback', '/LoginCallback', Record<never, never>, Record<never, never>>,
    '/LoginOidc': RouteRecordInfo<'/LoginOidc', '/LoginOidc', Record<never, never>, Record<never, never>>,
  }
}
